#!/bin/bash

########################################################################
# PBS directives, ie arguments to qsub. Learn more by running "man qsub"  
########################################################################

#PBS -lnodes=1:ppn=8

## This is the max run-time allowed  hr:min:sec
#PBS -l walltime=02:30:00 

## This is the filename for all printed output from your code
#PBS -N list1

## This line ensures the script runs in Bash
#PBS -S /bin/bash

## This line joins the output and error to print to the same file
#PBS -j oe

########################################################################
########################################################################


########################################################################
# Load MPI and your custom Conda environment
########################################################################

## Remember, to create an anaconda environment with our required python packages, do the
## following commands.  But, you should have done this during the CARC tutorial, so do not
## repeat these steps, unless you missed the tutorial.
#   $ module load anaconda 
#   $ conda create --name wheeler_mpi_py2_2019 python=3 mpi4py numpy scipy ipython matplotlib
 
module load openmpi-3.1.3-intel-19.0.4-uckhgnu
module load anaconda
source activate wheeler_mpi_py3_2019
########################################################################
########################################################################


########################################################################
# Now, change directory into the batch system's preferred scratch directory
# (don't worry about this now)
########################################################################
# Change to the directory where you submitted this script and typed qsub 
cd $PBS_O_WORKDIR
########################################################################
########################################################################



########################################################################
# Now, run your program.  Just change the below filename to run a 
# different program. 
########################################################################
mpirun -machinefile $PBS_NODEFILE -np 8 python simulation2.py
########################################################################
########################################################################


